// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_zone_1_completed = "CgkI06_d_r0LEAIQAQ"; // <GPGSID>
        public const string achievement_zone_3_completed = "CgkI06_d_r0LEAIQAw"; // <GPGSID>
        public const string leaderboard_zone_2_completion_time = "CgkI06_d_r0LEAIQBw"; // <GPGSID>
        public const string leaderboard_zone_5_completion_time = "CgkI06_d_r0LEAIQCg"; // <GPGSID>
        public const string leaderboard_zone_3_completion_time = "CgkI06_d_r0LEAIQCA"; // <GPGSID>
        public const string achievement_zone_5_completed = "CgkI06_d_r0LEAIQBQ"; // <GPGSID>
        public const string leaderboard_zone_1_completion_time = "CgkI06_d_r0LEAIQBg"; // <GPGSID>
        public const string achievement_zone_2_completed = "CgkI06_d_r0LEAIQAg"; // <GPGSID>
        public const string leaderboard_zone_4_completion_time = "CgkI06_d_r0LEAIQCQ"; // <GPGSID>
        public const string leaderboard_zone_6_completion_time = "CgkI06_d_r0LEAIQDA"; // <GPGSID>
        public const string achievement_zone_4_completed = "CgkI06_d_r0LEAIQBA"; // <GPGSID>

}

